version: "3.9"
services:
  nginx:
    build: ./nginxFrontend
    volumes:
      - type: bind
        source: /home/ec2-user/certs
        target: /etc/letsencrypt/live/mtabusalerts.com
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: ./busAlertsBackend
    volumes:
      - logs:/app/logs
volumes:
  logs:

